version: "3.2"

services:
  nginx:
    image: nginx
    volumes:
     - .:/var/www
     - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
     - 8099:80
     - 443:443
    depends_on:
      - php

  php:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    depends_on:
      - dbMain_postgres

  dbMain_postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"

