version: "3.2"

services:
  nginx:
    image: nginx
    volumes:
      - .:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8099:80 #
      - 443:443
    depends_on:
      - php

  php:
    build:
      context: .  #
    volumes:
      - .:/var/www
    depends_on:
      - dbMain_postgres
    command: /bin/sh -c "php artisan migrate --force && php-fpm"

  dbMain_postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hotel2
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pg_data:
